version: '1.0'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${DATABASE:-rails_tutorial_development}
  app:
    build: .
    command: rails server -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:
